# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qdptplotter.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(815, 656)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 19, 791, 621))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 10, 0, 1, 9, QtCore.Qt.AlignHCenter)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(8, "")
        self.gridLayout.addWidget(self.comboBox_3, 7, 1, 1, 3)
        self.comboBox_1 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout.addWidget(self.comboBox_1, 5, 1, 1, 3)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 9, 1, 1, 3)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 20, 0, 1, 9, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 17, 4, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 5, 5, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 17, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 18, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 22, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 3, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 4, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 6, 5, 1, 3)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 18, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 4, 0, 1, 9, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 18, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 17, 6, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout.addWidget(self.doubleSpinBox_7, 18, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 21, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout.addWidget(self.doubleSpinBox_8, 18, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.pathToQDPTFilesLabel = QtWidgets.QLabel(self.layoutWidget)
        self.pathToQDPTFilesLabel.setObjectName("pathToQDPTFilesLabel")
        self.gridLayout.addWidget(self.pathToQDPTFilesLabel, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 1, 1, 3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 18, 5, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 4, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout.addWidget(self.doubleSpinBox_4, 17, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 21, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(8, "")
        self.gridLayout.addWidget(self.comboBox_8, 7, 5, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 25, 0, 1, 9)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 1, 0, 1, 9)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 17, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 4, 1, 3, QtCore.Qt.AlignRight)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 4, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 8, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 21, 5, 1, 3)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        icon = QtGui.QIcon.fromTheme("hline")
        self.comboBox_9.addItem(icon, "")
        self.gridLayout.addWidget(self.comboBox_9, 8, 5, 1, 3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 21, 1, 1, 3)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 24, 0, 1, 9)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        icon = QtGui.QIcon.fromTheme("hline")
        self.comboBox_4.addItem(icon, "")
        self.gridLayout.addWidget(self.comboBox_4, 8, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 17, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 3, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout.addWidget(self.doubleSpinBox_5, 17, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 6)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 22, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMouseTracking(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 3, QtCore.Qt.AlignRight)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout.addWidget(self.comboBox_10, 9, 5, 1, 3)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout.addWidget(self.doubleSpinBox_6, 17, 7, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_21.setText(_translate("Form", " *** GRID SETTINGS *** "))
        self.comboBox_3.setItemText(0, _translate("Form", "blue"))
        self.comboBox_3.setItemText(1, _translate("Form", "orange"))
        self.comboBox_3.setItemText(2, _translate("Form", "green"))
        self.comboBox_3.setItemText(3, _translate("Form", "red"))
        self.comboBox_3.setItemText(4, _translate("Form", "cyan"))
        self.comboBox_3.setItemText(5, _translate("Form", "magenta"))
        self.comboBox_3.setItemText(6, _translate("Form", "yellow"))
        self.comboBox_3.setItemText(7, _translate("Form", "black"))
        self.comboBox_1.setItemText(0, _translate("Form", "-"))
        self.comboBox_1.setItemText(1, _translate("Form", "--"))
        self.comboBox_1.setItemText(2, _translate("Form", "-."))
        self.comboBox_1.setItemText(3, _translate("Form", ".."))
        self.comboBox_5.setItemText(0, _translate("Form", "0"))
        self.comboBox_5.setItemText(1, _translate("Form", "1"))
        self.comboBox_5.setItemText(2, _translate("Form", "2"))
        self.comboBox_5.setItemText(3, _translate("Form", "3"))
        self.comboBox_5.setItemText(4, _translate("Form", "4"))
        self.comboBox_5.setItemText(5, _translate("Form", "5"))
        self.comboBox_5.setItemText(6, _translate("Form", "6"))
        self.comboBox_5.setItemText(7, _translate("Form", "7"))
        self.comboBox_5.setItemText(8, _translate("Form", "8"))
        self.comboBox_5.setItemText(9, _translate("Form", "9"))
        self.comboBox_5.setItemText(10, _translate("Form", "10"))
        self.label_18.setText(_translate("Form", " *** OUTPUT PARAMETERS*** "))
        self.label_15.setText(_translate("Form", "Ymin"))
        self.comboBox_6.setItemText(0, _translate("Form", "-"))
        self.comboBox_6.setItemText(1, _translate("Form", "--"))
        self.comboBox_6.setItemText(2, _translate("Form", "-."))
        self.comboBox_6.setItemText(3, _translate("Form", ".."))
        self.label_16.setText(_translate("Form", "Xmax"))
        self.label_17.setText(_translate("Form", "Scale size"))
        self.label_3.setText(_translate("Form", "Line style"))
        self.comboBox_2.setItemText(0, _translate("Form", "2"))
        self.comboBox_2.setItemText(1, _translate("Form", "3"))
        self.comboBox_2.setItemText(2, _translate("Form", "4"))
        self.comboBox_2.setItemText(3, _translate("Form", "5"))
        self.comboBox_2.setItemText(4, _translate("Form", "6"))
        self.comboBox_2.setItemText(5, _translate("Form", "7"))
        self.comboBox_2.setItemText(6, _translate("Form", "8"))
        self.comboBox_2.setItemText(7, _translate("Form", "9"))
        self.comboBox_2.setItemText(8, _translate("Form", "10"))
        self.label_12.setText(_translate("Form", "Marker style"))
        self.label_19.setText(_translate("Form", "Axis width"))
        self.label_20.setText(_translate("Form", "*** LINES STYLES *** "))
        self.label_4.setText(_translate("Form", "Line width"))
        self.label_23.setText(_translate("Form", "Title"))
        self.label_14.setText(_translate("Form", "Ymax"))
        self.label_24.setText(_translate("Form", "Ereorg"))
        self.label_5.setText(_translate("Form", "Line color"))
        self.pathToQDPTFilesLabel.setText(_translate("Form", "Path to QDPT files"))
        self.lineEdit_2.setText(_translate("Form", "Energy profile"))
        self.label_10.setText(_translate("Form", "Line width"))
        self.label_25.setText(_translate("Form", "Energy Gap"))
        self.comboBox_8.setItemText(0, _translate("Form", "orange"))
        self.comboBox_8.setItemText(1, _translate("Form", "blue"))
        self.comboBox_8.setItemText(2, _translate("Form", "green"))
        self.comboBox_8.setItemText(3, _translate("Form", "red"))
        self.comboBox_8.setItemText(4, _translate("Form", "cyan"))
        self.comboBox_8.setItemText(5, _translate("Form", "magenta"))
        self.comboBox_8.setItemText(6, _translate("Form", "yellow"))
        self.comboBox_8.setItemText(7, _translate("Form", "black"))
        self.pushButton.setText(_translate("Form", "Plot"))
        self.label_22.setText(_translate("Form", "--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.label_7.setText(_translate("Form", "Marker size"))
        self.label_8.setText(_translate("Form", "State №"))
        self.label_11.setText(_translate("Form", "Line color"))
        self.label_13.setText(_translate("Form", "Marker size"))
        self.toolButton.setText(_translate("Form", "..."))
        self.comboBox_9.setItemText(0, _translate("Form", "."))
        self.comboBox_9.setItemText(1, _translate("Form", "o"))
        self.comboBox_9.setItemText(2, _translate("Form", "v"))
        self.comboBox_9.setItemText(3, _translate("Form", "^"))
        self.comboBox_9.setItemText(4, _translate("Form", "s"))
        self.comboBox_9.setItemText(5, _translate("Form", "+"))
        self.comboBox_9.setItemText(6, _translate("Form", "x"))
        self.comboBox_9.setItemText(7, _translate("Form", "D"))
        self.comboBox_9.setItemText(8, _translate("Form", "d"))
        self.comboBox_9.setItemText(9, _translate("Form", "_"))
        self.label_26.setText(_translate("Form", "--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.comboBox_4.setItemText(0, _translate("Form", "."))
        self.comboBox_4.setItemText(1, _translate("Form", "o"))
        self.comboBox_4.setItemText(2, _translate("Form", "v"))
        self.comboBox_4.setItemText(3, _translate("Form", "^"))
        self.comboBox_4.setItemText(4, _translate("Form", "s"))
        self.comboBox_4.setItemText(5, _translate("Form", "+"))
        self.comboBox_4.setItemText(6, _translate("Form", "x"))
        self.comboBox_4.setItemText(7, _translate("Form", "D"))
        self.comboBox_4.setItemText(8, _translate("Form", "d"))
        self.comboBox_4.setItemText(9, _translate("Form", "_"))
        self.label.setText(_translate("Form", "Xmin"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "2"))
        self.comboBox.setItemText(2, _translate("Form", "3"))
        self.comboBox.setItemText(3, _translate("Form", "4"))
        self.comboBox.setItemText(4, _translate("Form", "5"))
        self.comboBox.setItemText(5, _translate("Form", "6"))
        self.comboBox.setItemText(6, _translate("Form", "7"))
        self.comboBox.setItemText(7, _translate("Form", "8"))
        self.comboBox.setItemText(8, _translate("Form", "9"))
        self.label_9.setText(_translate("Form", "Line style"))
        self.lineEdit.setText(_translate("Form", "Enter path to folder with QDPT .out files  --->"))
        self.label_27.setText(_translate("Form", "ΔG"))
        self.label_6.setText(_translate("Form", "Marker style"))
        self.label_2.setText(_translate("Form", "State №"))
        self.comboBox_10.setItemText(0, _translate("Form", "0"))
        self.comboBox_10.setItemText(1, _translate("Form", "1"))
        self.comboBox_10.setItemText(2, _translate("Form", "2"))
        self.comboBox_10.setItemText(3, _translate("Form", "3"))
        self.comboBox_10.setItemText(4, _translate("Form", "4"))
        self.comboBox_10.setItemText(5, _translate("Form", "5"))
        self.comboBox_10.setItemText(6, _translate("Form", "6"))
        self.comboBox_10.setItemText(7, _translate("Form", "7"))
        self.comboBox_10.setItemText(8, _translate("Form", "8"))
        self.comboBox_10.setItemText(9, _translate("Form", "9"))
        self.comboBox_10.setItemText(10, _translate("Form", "10"))
